[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src https://*; font-src fonts.gstatic.com; style-src 'self' fonts.googleapis.com 'unsafe-inline'; child-src 'none';"
