name: Main Workflow

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install and lint
        run: |
          npm ci
          npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install and test
        run: |
          npm ci
          npx playwright install-deps
          npm run test:all

      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1

      - name: Deploy to netlify
        uses: jsmrcaga/action-netlify-deploy@v1.7.2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: Preview ${{ env.BRANCH_NAME }}
          build_directory: dist
          deploy_alias: ${{ env.BRANCH_NAME }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.BRANCH_NAME == 'main' }}

      - name: Status check
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify Site
          state: success
          target_url: https://${{ env.BRANCH_NAME }}--amenity-finder.netlify.app

